server:
  port: 8083

spring:
  application:
    name: recommender-service

logging:
  level:
    root: INFO
    com.example.recommender: DEBUG

clients:
  catalog:
    base-url: http://localhost:8081
  event:
    base-url: http://localhost:8082

